spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # Auth Service Routes
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # Activity Service Routes
        - id: activity-service
          uri: ${ACTIVITY_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/activities/**
          filters:
            - StripPrefix=0

        # Report Service Routes
        - id: report-service
          uri: ${REPORT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=0

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
