spring:
  application:
    name: report-service

server:
  port: 8083

activity-service:
  url: ${ACTIVITY_SERVICE_URL:http://localhost:8082}

logging:
  level:
    com.historial.report: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
